project:
  type: website
  output-dir: docs
  
website:
  title: "MY WEB SITE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: linkedin
        href: www.linkedin.com/in/jingyi-yang82
      - icon: github
        href: https://github.com/Jing202822?tab=repositories
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Jingyi Yang"

format:
  html:
    theme: cerulean
    toc: true

editor: source

